blueprint:
  name: Pausable Single Operation State by Power Consumption
  description: |
    
    # Pausable Single Operation State by Power Consumption

    A template sensor which holds an operational state based on a referenced power consumption entity.
    
    It assumes that the 'running' operation can be paused and resumed before regular finish.

    The states are 'off', 'on', 'running', 'paused or finished', 'finished', and 'interrupted by power supply'.
    
    ## More Info

    ℹ️ Version 2025.12.2

  domain: template
  source_url: https://github.com/damien-sorin/homeassistant-blueprints/blob/main/template/pausable-single-operation-state-by-power-consumption.yaml
  input:

    reference_power_consumption_entity:
      name: Current Power Consumption Sensor
      description: sensor entity delivering the current power consumption in Watt.
      selector:
        entity:
          multiple: false
          filter:
            device_class: power

    power_value_off_upper:
      name: Off State - Upper Bound Power Consumption   
      description: The highest power consumption to assume the device is in 'off' state.
      default: 0.1
      selector:
        number:
          min: 0
          max: 3600
          step: 0.1
          unit_of_measurement: W
          mode: box

    power_value_idle_lower:
      name: On State - Lower Bound Power Consumption   
      description: The lowest power consumption value to assume the device is in 'on' state.
      default: 0.2
      selector:
        number:
          min: 0
          max: 3600
          step: 0.1
          unit_of_measurement: W
          mode: box

    power_value_idle_upper:
      name: On State - Upper Bound Power Consumption   
      description: The highest power consumption value to assume the device is in 'on' state.
      default: 4.0
      selector:
        number:
          min: 0
          max: 3600
          step: 0.1
          unit_of_measurement: W
          mode: box

    power_value_running_lower:
      name: Running State - Lower Bound Power Consumption   
      description: The lowest power consumption value to assume the device is in 'running' state.
      default: 30.0
      selector:
        number:
          min: 0
          max: 3600
          step: 0.1
          unit_of_measurement: W
          mode: box

    paused_to_finished_delay:
      name: Pause Duration Threshold
      description: Time in seconds to consider the device as finished instead of paused.
      default: 300
      selector:
        number:
          min: 10
          max: 3600
          step: 1
          unit_of_measurement: s
          mode: box

variables:
  _power_sensor: !input reference_power_consumption_entity

  _power_value_off_upper: !input power_value_off_upper
  _power_value_idle_lower: !input power_value_idle_lower
  _power_value_idle_upper: !input power_value_idle_upper
  _power_value_running_lower: !input power_value_running_lower

  _state_unknown: 'unknown'
  _state_off: 'off'
  _state_on: 'on'
  _state_running: 'running'
  _state_paused_or_finished: 'paused or finished'
  _state_finished: 'finished'
  _state_interrupted: 'interrupted by power supply'
  
  _paused_to_finished_delay: !input paused_to_finished_delay

sensor:
  availability: >
    {{ states(_power_sensor) not in ('unknown', 'unavailable') }}
  state: >
    {% set next_state = _state_unknown %}

    {% set power_sensor_state = states(_power_sensor) %}
    
    {% if power_sensor_state | is_number %}

      {% set current_power = power_sensor_state | float(0) %}

      {% set current_state = this.state %}
      {% if current_state in [None, '', 'unavailable'] %}
          {% set current_state = _state_unknown %}
      {% endif %}

      {% set next_state = current_state %}

      {% if current_state == _state_unknown %}

        {% if current_power < _power_value_idle_lower %}
          {% set next_state = _state_off %}
        {% elif current_power < _power_value_running_lower %}
          {% set next_state = _state_on %}
        {% else %}
          {% set next_state = _state_running %}
        {% endif %}

      {% elif current_state == _state_off %}

        {% if current_power >= _power_value_idle_lower %}
          {% set next_state = _state_on %}
        {% endif %}

      {% elif current_state == _state_on %}

        {% if current_power <= _power_value_off_upper %}
          {% set next_state = _state_off %}
        {% elif current_power >= _power_value_running_lower %}
          {% set next_state = _state_running %}
        {% endif %}

      {% elif current_state == _state_running %}

        {% if current_power <= _power_value_off_upper %}
          {% set next_state = _state_interrupted %}
        {% elif current_power <= _power_value_idle_upper %}
          {% set next_state = _state_paused_or_finished %}
        {% endif %}
      
      {% elif current_state == _state_paused_or_finished %}

        {% if current_power <= _power_value_off_upper %}
          {% set next_state = _state_finished %}
        {% elif current_power >= _power_value_running_lower %}
          {% set next_state = _state_running %}
        {% endif %}

        {% if next_state == current_state %}

          {% set last_changed = as_timestamp(this.last_changed, 0) %}
          {% set paused_or_finished_duration = now().timestamp() - last_changed %}

          {% if paused_or_finished_duration > _paused_to_finished_delay %}
            {% set next_state = _state_finished %}
          {% endif %}

        {% endif %}

      {% elif current_state == _state_finished %}

        {% if current_power <= _power_value_off_upper %}
          {% set next_state = _state_off %}
        {% elif current_power >= _power_value_running_lower %}
          {% set next_state = _state_running %}
        {% endif %}

      {% elif current_state == _state_interrupted %}

        {% if current_power < _power_value_idle_lower %}
          {% set next_state = _state_off %}
        {% elif current_power < _power_value_running_lower %}
          {% set next_state = _state_on %}
        {% else %}
          {% set next_state = _state_running %}
        {% endif %}
      
      {% endif %}
    
    {% endif %}

    {{ next_state }}
